name: Test Build

on: [push]

jobs:
  build:
    name: Deepin-Unioncode ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Install Dep
        run: sudo apt-get update & sudo apt-get upgrade & sudo apt -y build-dep ./

      - name: Set Build Env
        run: cmake -B build -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build
      
      - name: Install App
        run: sudo cmake --build build --target install
